version: "3.8"

services:
  b-shop-haproxy:
    container_name: b-shop-haproxy
    image: haproxy:alpine
    restart: always
    ports:
      - "80:8080"
      - "15672:9000"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    networks:
      - b-shop-network

networks:
  b-shop-network:
    external: true