# docker-compose up -d
# docker-compose down -v
version: "3.8"
services:
  b-shop-front:
    container_name: b-shop-front
    image: mentoring-gitlab.gabia.com:5050/mentee/mentee_2023.01/team/g-market/gabia-b-shop-frontend:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8083:8080"
    networks:
      - b-shop-network

networks:
  b-shop-network:
    external: true